@port = 8081

### Create Enterprise
POST http://localhost:{{port}}/enterprises HTTP/1.1
Content-Type: application/json

{
    "name": "Cloud Tecno SAS",
    "commercial_name": "Cloud Tecno",
    "slug": "cloud_tecno",
    "sub_domain": "cloudtecno",
    "email": "super-admin@cloudtecno.com",
    "password": "securepassword123",
    "dv": "1",
    "phone": "5551234",
    "municipality_id": "05001",
    "municipality": "Medellin"
}

### Login
POST http://localhost:{{port}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "super-admin@cloudtecno.com",
    "password": "securepassword123"
}

### Roles
GET http://localhost:{{port}}/roles HTTP/1.1

